kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: console-link-role
rules:
  - verbs:
    - get
    - create
    - patch
    apiGroups:
    - console.openshift.io
    resources:
    - consolelinks
